apiVersion: v1
kind: Service
metadata:
  name: web-dev-tools-service
spec:
  selector:
    app: web-dev-tools
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
